# Generated by Django 5.0.2 on 2024-02-11 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_emails_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name_plural': 'Emails'},
        ),
    ]
