# Generated by Django 5.0.2 on 2024-02-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='secondary_code',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
