# Generated by Django 5.0.2 on 2024-03-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_newuser_clicks_newuser_sales_alter_newuser_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='code',
            field=models.CharField(default='8UORL_1709832669_6P6CR', max_length=150),
        ),
    ]
