# Generated by Django 5.0.2 on 2024-03-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_newuser_stripe_id_alter_newuser_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='country',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='code',
            field=models.CharField(default='GC1WV_1710005720_TJA4F', max_length=150),
        ),
    ]
