# Generated by Django 5.0.2 on 2024-03-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_newuser_country_alter_newuser_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='code',
            field=models.CharField(default='8AYMD_1711749804_B75M1', max_length=150),
        ),
    ]
