# Generated by Django 5.0.2 on 2024-05-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_newuser_verified_alter_newuser_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='code',
            field=models.CharField(default='9URQE_1715270650_N7FIX', max_length=150),
        ),
    ]
