# Generated by Django 5.0.2 on 2024-05-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_newuser_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='code',
            field=models.CharField(default='PA79R_1715279494_63XR2', max_length=150),
        ),
    ]
